play/core/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import patterns, url
from django.conf.urls.static import static
from play.core.views import FilmeList, FilmeDetail, GeneroDetail, AtorDetail


urlpatterns = patterns('play.core.views',

    url(r'^filmes/(?P<slug>[-_\w]+)/$',
        FilmeDetail.as_view(),
        name='film-detail'),

    url(r'^generos/(?P<slug>[-_\w]+)/$',
        GeneroDetail.as_view(),
        name='genero-detail'),

    url(r'^atores/(?P<slug>[-_\w]+)/$',
        AtorDetail.as_view(),
        name='ator-detail'),

    url(r'^$', FilmeList.as_view(), name='home'),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

play/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',

    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include("play.core.urls", namespace="core"))
)

play/core/models.py
from django.db import models
from django.conf import settings
from django_resized import ResizedImageField
from django.template.defaultfilters import slugify
from django.db.models.query import QuerySet


class FilmeQuerySet(QuerySet):
    def filmes_relacionados(self, filme_id, generos, atores):
        return self.raw("""
        SELECT f.*, count(distinct fg.genero_id) count_generos,
        count(distinct fa.ator_id) count_ator
        FROM core_filme f, core_filme_generos fg, core_filme_atores fa
        where fa.filme_id = f.id
        and fg.filme_id = f.id
        and fa.ator_id in (%s)
        and fg.genero_id in (%s)
        and f.id != '%s'
        group by f.id
        order by count_generos desc, count_ator desc
            """ % (",".join(generos), ",".join(atores), filme_id))


class FilmeManager(models.Manager):

    def get_queryset(self):
        return FilmeQuerySet(self.model, using=self._db)

    def filmes_relacionados(self, filme):
        if not isinstance(filme, Filme):
            raise ValueError("The filme argument must be a Filme instance")

        generos = map(lambda genero: str(genero.id), filme.generos.all()) or []
        atores = map(lambda ator: str(ator.id), filme.atores.all()) or []
        return self.get_queryset().filmes_relacionados(filme.id, generos, atores)


class Filme(models.Model):
    nome = models.CharField(max_length=100, unique=True)
    sinopse = models.TextField(max_length=11)
    capa = ResizedImageField(upload_to='filmes/', size=[220, 283])
    generos = models.ManyToManyField('Genero')
    atores = models.ManyToManyField('Ator')
    slug = models.SlugField()
    created_at = models.DateTimeField(auto_now_add=True,
                                      verbose_name="criado em")

    objects = FilmeManager()

    def image_tag(self):
        return u'<img src="%s%s" width="168" heigth="216" />' % (settings.MEDIA_URL, self.capa)

    image_tag.short_description = 'Capa'
    image_tag.allow_tags = True

    def __unicode__(self):
        return self.nome

    def save(self, *args, **kwargs):
        self.slug = slugify(self.nome)

        super(Filme, self).save(*args, **kwargs)


class Genero(models.Model):
    nome = models.CharField(max_length=20, unique=True)
    slug = models.SlugField()

    def __unicode__(self):
        return self.nome

    def get_absolute_url(self):
        return "/generos/%s/" % self.slug

    def save(self, *args, **kwargs):
        self.slug = slugify(self.nome)

        super(Genero, self).save(*args, **kwargs)


class Ator(models.Model):
    nome = models.CharField(max_length=20, unique=True)
    pais = models.CharField(max_length=20)
    foto = ResizedImageField(upload_to='atores/', size=[160, 100])
    slug = models.SlugField()

    def __unicode__(self):
        return self.nome

    def get_absolute_url(self):
        return "/atores/%d/" % self.slug

    def save(self, *args, **kwargs):
        self.slug = slugify(self.nome)

        super(Ator, self).save(*args, **kwargs)

play/core/views.py
from play.core.models import Filme, Genero, Ator
from django.views.generic import ListView, DetailView
from django.shortcuts import get_object_or_404


class FilmeList(ListView):

    def get_queryset(self):
        queryset = Filme.objects.all()
        order = self.request.GET.get("order", "asc")
        if order == "desc":
            queryset = Filme.objects.order_by("-id")

        return queryset


class FilmeDetail(DetailView):
    model = Filme

    def get_object(self):
        filme = get_object_or_404(Filme, slug=self.kwargs['slug'])
        return filme

    def get_context_data(self, **kwargs):
        context = super(FilmeDetail, self).get_context_data(**kwargs)
        context['filmes_relacionados'] = Filme.objects.filmes_relacionados(self.get_object())
        return context


class GeneroDetail(DetailView):
    model = Genero

    def get_queryset(self):
        queryset = Genero.objects.all()
        order = self.request.GET.get("order", "asc")
        if order == "desc":
            queryset = self.get_object().filme_set.order_by("-id")

        return queryset

    def get_object(self):
        genero = get_object_or_404(Genero, slug=self.kwargs['slug'])
        return genero

    def get_context_data(self, **kwargs):
        order = self.request.GET.get("order", "asc")
        context = super(GeneroDetail, self).get_context_data(**kwargs)
        context['filmes'] = self.get_object().filme_set.all()

        if order == "desc":
            context['filmes'] = self.get_object().filme_set.order_by("-id")

        return context


class AtorDetail(DetailView):
    model = Ator

    def get_object(self):
        ator = get_object_or_404(Ator, slug=self.kwargs['slug'])
        return ator

play/core/templates/core/ator_detail.html
{% extends 'core/base.html' %}

{% block content %}
<main id="Content" class="fix">
	<header class="fix">
		<h1>Atores</h1>
	</header>
	
	<section id="Infos" class='fix'>
		<figure class="fl"><img src="{{ MEDIA_URL }}{{ ator.foto }}" alt=""></figure>

		<article class="fl">
			<p class="tit">Ator</p>
			<h2>{{ ator.nome }}</h2>
			<p class="txt"><strong>País:</strong> {{ ator.pais }}</p>
			
		</article>

	</section>

	<section id="listagem" class='fix'>
		{% include 'core/filme_list_snippet.html' with filmes=ator.filme_set.all %}
	</section>

</main>
{% endblock content %}

play/core/templates/core/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Storm Security - Teste Python</title>

    <link rel="stylesheet" href="{{ STATIC_URL }}css/reset.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/comum.css">
</head>
<body>
    <header id="header">
        <div class="content">
            <a href="{% url 'core:home' %}" class="home" title="voltar para home"></a>
        </div>
    </header>
    <main id="Content" class="fix">
        {% block content %} {% endblock content %}
    </main>
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
    <script type="text/javascript">
        $("#sort_form select").on("change", function () {
            $("#sort_form").submit();
        })
    </script>
</body>
</html>

play/core/templates/core/filme_detail.html
{% extends 'core/base.html' %}

{% block content %}
<main id="Content" class="fix">
    <header class="fix">
        <h1>{{ filme.nome }}</h1>
    </header>
    
    <section id="Infos" class='fix'>
        <figure class="fl"><img src="{{ MEDIA_URL }}{{ filme.capa }}" alt=""></figure>

        <article class="fl">
            <p class="tit">Sinopse:</p>
            <p class="txt">{{ filme.sinopse }}</p>
            <p class="tit">Genero:</p>
            <p class="txt">
            {% for genero in filme.generos.all %}
                <a href="/generos/{{ genero.slug }}/">{{ genero.nome }}</a>, 
            {% endfor %}

            </p>
            <p class="tit">Atores:</p>
            <p class="txt">
            {% for ator in filme.atores.all %}
                <a href="/atores/{{ ator.slug }}/">{{ ator.nome }}</a>, 
            {% endfor %}
            </p>
        </article>

    </section>

    <section id="listagem" class='fix'>
        <header class="fix">
            <h2>Filmes Relacionados</h2>
        </header>
        {% include 'core/filme_list_snippet.html' with filmes=filmes_relacionados %}
    </section>

</main>
{% endblock content %}

play/core/templates/core/filme_list.html
{% extends 'core/base.html' %}

{% block content %}
<header class="fix">
	<h1 class="fl">Listagem de filmes :: Teste no AppleBee </h1>
	{% include 'core/form_sort_snippet.html' %}
</header>

<section id="listagem" class='fix'>
	{% include 'core/filme_list_snippet.html' with filmes=object_list %}
</section>
{% endblock content %}

play/core/templates/core/filme_list_snippet.html
<ul>
    {% for filme in filmes %}
        <li class="fl">
            <a href="/filmes/{{ filme.slug }}">
                <img src="{{ MEDIA_URL }}{{ filme.capa }}" alt="">
            </a>
        </li>
    {% empty %}
        <h1>Sem filmes a serem exibidos</h1>
    {% endfor %}
</ul>

play/core/templates/core/form_sort_snippet.html
<form action="" id="sort_form">
    <select name="order" class="fr">
        <option value="">Ordenar por:</option>
        <option value="asc">a - z</option>
        <option value="desc">z - a</option>
    </select>
</form>

play/core/templates/core/genero_detail.html
{% extends 'core/base.html' %}

{% block content %}
<main id="Content" class="fix">
	<header class="fix">
		<h1 class="fl">{{ genero.nome }}</h1>
		{% include 'core/form_sort_snippet.html' %}
	</header>

	<section id="listagem" class='fix'>
		{% include 'core/filme_list_snippet.html' %}
	</section>

</main>
{% endblock content %}

play/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block content %}
<header class="fix">
	<h1 class="fl">Listagem de filmes</h1>
	<form action="">
		<select name="" id="" class="fr">
			<option value="">Ordenar por:</option>
			<option value="">a - z</option>
			<option value="">z - a</option>
		</select>
	</form>
</header>

<section id="listagem" class='fix'>
	<ul>
		<li class="fl"><a href="interna.html"><img src="{{ STATIC_URL }}img/cartaz1.jpg" alt=""></a></li>
		<li class="fl"><a href="interna.html"><img src="{{ STATIC_URL }}img/cartaz2.jpg" alt=""></a></li>
		<li class="fl"><a href="interna.html"><img src="{{ STATIC_URL }}img/cartaz3.jpg" alt=""></a></li>
		<li class="fl"><a href="interna.html"><img src="{{ STATIC_URL }}img/cartaz4.jpg" alt=""></a></li>
		<li class="fl last"><a href="interna.html"><img src="{{ STATIC_URL }}img/cartaz5.jpg" alt=""></a></li>
		<li class="fl"><a href="interna.html"><img src="{{ STATIC_URL }}img/cartaz6.jpg" alt=""></a></li>
		<li class="fl"><a href="interna.html"><img src="{{ STATIC_URL }}img/cartaz7.jpg" alt=""></a></li>
		<li class="fl"><a href="interna.html"><img src="{{ STATIC_URL }}img/cartaz8.jpg" alt=""></a></li>
		<li class="fl"><a href="interna.html"><img src="{{ STATIC_URL }}img/cartaz9.jpg" alt=""></a></li>
		<li class="fl last"><a href="interna.html"><img src="{{ STATIC_URL }}img/cartaz10.jpg" alt=""></a></li>
		<li class="fl"><a href="interna.html"><img src="{{ STATIC_URL }}img/cartaz11.jpg" alt=""></a></li>
	</ul>
</section>
{% endblock content %}

play/core/templates/core/interna.html
{% extends 'core/base.html' %}

{% block content %}
<main id="Content" class="fix">
	<header class="fix">
		<h1>Nome do filme</h1>
	</header>
	
	<section id="Infos" class='fix'>
		<figure class="fl"><img src="{{ STATIC_URL }}img/cartaz1-interna.jpg" alt=""></figure>

		<article class="fl">
			<p class="tit">Sinopse:</p>
			<p class="txt">A agente especial do FBI Sarah Ashburn (Sandra Bullock) e a policial Shannon Mullins (Melissa McCarthy) não podiam ser mais imcompatíveis. Quando precisam juntar forças para trazer um perigoso traficante de drogas, elas se tornarão algo que ninguém esperava: amigas.</p>
			<p class="tit">Genero:</p>
			<p class="txt"><a href="genero.html">Comédia</a> e <a href="genero.html">Ação</a>.</p>

			<p class="tit">Atores:</p>
			<p class="txt"><a href="artista.html">Marlon Wayans</a>, <a href="artista.html">Melissa McCarthy</a> e <a href="artista.html">Sandra Bullock</a>.</p>
		</article>

	</section>

	<section id="listagem" class='fix'>
		<header class="fix">
			<h2>Filmes Relacionados</h2>
		</header>
		<ul>
			<li class="fl"><a href="interna.html"><img src="{{ STATIC_URL }}img/cartaz2.jpg" alt=""></a></li>
			<li class="fl"><a href="interna.html"><img src="{{ STATIC_URL }}img/cartaz3.jpg" alt=""></a></li>
			<li class="fl"><a href="interna.html"><img src="{{ STATIC_URL }}img/cartaz4.jpg" alt=""></a></li>
			<li class="fl"><a href="interna.html"><img src="{{ STATIC_URL }}img/cartaz5.jpg" alt=""></a></li>
			<li class="fl last"><a href="interna.html"><img src="{{ STATIC_URL }}img/cartaz6.jpg" alt=""></a></li>
			<li class="fl"><a href="interna.html"><img src="{{ STATIC_URL }}img/cartaz7.jpg" alt=""></a></li>
			<li class="fl"><a href="interna.html"><img src="{{ STATIC_URL }}img/cartaz8.jpg" alt=""></a></li>
			<li class="fl"><a href="interna.html"><img src="{{ STATIC_URL }}img/cartaz9.jpg" alt=""></a></li>
			<li class="fl"><a href="interna.html"><img src="{{ STATIC_URL }}img/cartaz10.jpg" alt=""></a></li>
			<li class="fl last"><a href="interna.html"><img src="{{ STATIC_URL }}img/cartaz11.jpg" alt=""></a></li>
		</ul>
	</section>

</main>
{% endblock content %}